openapi: 3.1.0
info:
  title: "NEAR Protocol RPC: Block by ID"
  description: Retrieve block data using a specific block hash
  version: 1.0.0
servers:
  - url: "https://rpc.mainnet.fastnear.com"
    description: Mainnet
  - url: "https://rpc.testnet.fastnear.com"
    description: Testnet
paths:
  /:
    post:
      operationId: block_by_id
      summary: Get block by ID
      description: Retrieves block details using a specific block hash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [jsonrpc, id, method, params]
              properties:
                jsonrpc:
                  type: string
                  enum: ["2.0"]
                id:
                  type: string
                  example: fastnear
                method:
                  type: string
                  enum: [block]
                params:
                  type: object
                  required: [block_id]
                  properties:
                    block_id:
                      type: string
                      description: Base58-encoded block hash
            examples:
              mainnet:
                summary: Mainnet Block Example
                value:
                  jsonrpc: "2.0"
                  id: fastnear
                  method: block
                  params:
                    block_id: DYf4gXPNrdRE2JNCaKH7ZJyfAvk1vL13QNJK35qU6uvx
              testnet:
                summary: Testnet Block Example
                value:
                  jsonrpc: "2.0"
                  id: fastnear
                  method: block
                  params:
                    block_id: FLvphksgEysEbhr8uMqWkQoogjvk2UZrkiBGC3kcmaE5
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonRpcResponse"
components:
  schemas:
    JsonRpcResponse:
      type: object
      required: [jsonrpc, id]
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        id:
          oneOf:
            - type: string
            - type: number
        result:
          type: object
          properties:
            author:
              type: string
              description: NEAR account ID
            chunks:
              type: array
              items:
                type: object
                description: Contains main info about the chunk.
            header:
              type: object
              description: Contains main info about the block.
              properties:
                approvals:
                  type: array
                  items:
                    type: object
                block_body_hash:
                  type: [string, "null"]
                  description: Base58-encoded hash
                block_merkle_root:
                  type: string
                  description: Base58-encoded hash
                block_ordinal:
                  type: [integer, "null"]
                  format: uint64
                  minimum: 0
                challenges_result:
                  type: array
                  items:
                    type: object
                challenges_root:
                  type: string
                  description: Base58-encoded hash
                chunk_endorsements:
                  type: array
                  items:
                    type: object
                chunk_headers_root:
                  type: string
                  description: Base58-encoded hash
                chunk_mask:
                  type: array
                  items:
                    type: object
                chunk_receipts_root:
                  type: string
                  description: Base58-encoded hash
                chunk_tx_root:
                  type: string
                  description: Base58-encoded hash
                chunks_included:
                  type: integer
                  format: uint64
                  minimum: 0
                epoch_id:
                  type: string
                  description: Base58-encoded hash
                epoch_sync_data_hash:
                  type: [string, "null"]
                  description: Base58-encoded hash
                gas_price:
                  type: string
                  description: Amount in yoctoNEAR
                hash:
                  type: string
                  description: Base58-encoded hash
                height:
                  type: integer
                  format: uint64
                  minimum: 0
                last_ds_final_block:
                  type: string
                  description: Base58-encoded hash
                last_final_block:
                  type: string
                  description: Base58-encoded hash
                latest_protocol_version:
                  type: integer
                  format: uint32
                  minimum: 0
                next_bp_hash:
                  type: string
                  description: Base58-encoded hash
                next_epoch_id:
                  type: string
                  description: Base58-encoded hash
                outcome_root:
                  type: string
                  description: Base58-encoded hash
                prev_hash:
                  type: string
                  description: Base58-encoded hash
                prev_height:
                  type: [integer, "null"]
                  format: uint64
                  minimum: 0
                prev_state_root:
                  type: string
                  description: Base58-encoded hash
                random_value:
                  type: string
                  description: Base58-encoded hash
                rent_paid:
                  type: string
                  description: Amount in yoctoNEAR
                  default: "0"
                signature:
                  type: string
                  description: Base58-encoded cryptographic signature
                timestamp:
                  type: integer
                  description: Legacy json number. Should not be used.
                  format: uint64
                  minimum: 0
                timestamp_nanosec:
                  type: string
                total_supply:
                  type: string
                  description: Amount in yoctoNEAR
                validator_proposals:
                  type: array
                  items:
                    type: object
                validator_reward:
                  type: string
                  description: Amount in yoctoNEAR
                  default: "0"
              required:
                - height
                - epoch_id
                - next_epoch_id
                - hash
                - prev_hash
                - prev_state_root
                - chunk_receipts_root
                - chunk_headers_root
                - chunk_tx_root
                - outcome_root
                - chunks_included
                - challenges_root
                - timestamp
                - timestamp_nanosec
                - random_value
                - validator_proposals
                - chunk_mask
                - gas_price
                - total_supply
                - challenges_result
                - last_final_block
                - last_ds_final_block
                - next_bp_hash
                - block_merkle_root
                - approvals
                - signature
                - latest_protocol_version
          required: [author, header, chunks]
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
            data:
              type: object
