/* This file is auto-generated by scripts/generate-page-models.js. */
/* Do not edit it by hand; regenerate it via npm run sync:apis or npm run standalone:build. */

import allPageModels from "./generatedFastnearPageModels.json";

export const ALL_PAGE_MODELS = allPageModels;

export type GeneratedFastnearPageModel = (typeof ALL_PAGE_MODELS)[number];
