/* This file is auto-generated by scripts/generate-page-models.js. */
/* Do not edit it by hand; regenerate it via npm run sync:apis or npm run standalone:build. */

import rpcViewAccessKeyPageModel from "../standalone/generated/rpc-view-access-key-page-model.json";
import rpcViewAccessKeyListPageModel from "../standalone/generated/rpc-view-access-key-list-page-model.json";
import rpcViewAccountPageModel from "../standalone/generated/rpc-view-account-page-model.json";
import rpcBlockByHeightPageModel from "../standalone/generated/rpc-block-by-height-page-model.json";
import rpcBlockByIdPageModel from "../standalone/generated/rpc-block-by-id-page-model.json";
import rpcBlockEffectsPageModel from "../standalone/generated/rpc-block-effects-page-model.json";
import rpcCallFunctionPageModel from "../standalone/generated/rpc-call-function-page-model.json";
import rpcViewCodePageModel from "../standalone/generated/rpc-view-code-page-model.json";
import rpcViewGlobalContractCodePageModel from "../standalone/generated/rpc-view-global-contract-code-page-model.json";
import rpcViewGlobalContractCodeByAccountIdPageModel from "../standalone/generated/rpc-view-global-contract-code-by-account-id-page-model.json";
import rpcViewStatePageModel from "../standalone/generated/rpc-view-state-page-model.json";
import rpcEXPERIMENTALCongestionLevelPageModel from "../standalone/generated/rpc-EXPERIMENTAL-congestion-level-page-model.json";
import rpcEXPERIMENTALLightClientBlockProofPageModel from "../standalone/generated/rpc-EXPERIMENTAL-light-client-block-proof-page-model.json";
import rpcEXPERIMENTALLightClientProofPageModel from "../standalone/generated/rpc-EXPERIMENTAL-light-client-proof-page-model.json";
import rpcEXPERIMENTALProtocolConfigPageModel from "../standalone/generated/rpc-EXPERIMENTAL-protocol-config-page-model.json";
import rpcEXPERIMENTALSplitStorageInfoPageModel from "../standalone/generated/rpc-EXPERIMENTAL-split-storage-info-page-model.json";
import rpcChangesPageModel from "../standalone/generated/rpc-changes-page-model.json";
import rpcChunkByBlockShardPageModel from "../standalone/generated/rpc-chunk-by-block-shard-page-model.json";
import rpcChunkByHashPageModel from "../standalone/generated/rpc-chunk-by-hash-page-model.json";
import rpcClientConfigPageModel from "../standalone/generated/rpc-client-config-page-model.json";
import rpcGasPricePageModel from "../standalone/generated/rpc-gas-price-page-model.json";
import rpcGasPriceByBlockPageModel from "../standalone/generated/rpc-gas-price-by-block-page-model.json";
import rpcGenesisConfigPageModel from "../standalone/generated/rpc-genesis-config-page-model.json";
import rpcHealthPageModel from "../standalone/generated/rpc-health-page-model.json";
import rpcLatestBlockPageModel from "../standalone/generated/rpc-latest-block-page-model.json";
import rpcLightClientProofPageModel from "../standalone/generated/rpc-light-client-proof-page-model.json";
import rpcMaintenanceWindowsPageModel from "../standalone/generated/rpc-maintenance-windows-page-model.json";
import rpcMetricsPageModel from "../standalone/generated/rpc-metrics-page-model.json";
import rpcNetworkInfoPageModel from "../standalone/generated/rpc-network-info-page-model.json";
import rpcNextLightClientBlockPageModel from "../standalone/generated/rpc-next-light-client-block-page-model.json";
import rpcStatusPageModel from "../standalone/generated/rpc-status-page-model.json";
import rpcEXPERIMENTALReceiptPageModel from "../standalone/generated/rpc-EXPERIMENTAL-receipt-page-model.json";
import rpcEXPERIMENTALTxStatusPageModel from "../standalone/generated/rpc-EXPERIMENTAL-tx-status-page-model.json";
import rpcBroadcastTxAsyncPageModel from "../standalone/generated/rpc-broadcast-tx-async-page-model.json";
import rpcBroadcastTxCommitPageModel from "../standalone/generated/rpc-broadcast-tx-commit-page-model.json";
import rpcSendTxPageModel from "../standalone/generated/rpc-send-tx-page-model.json";
import rpcTxStatusPageModel from "../standalone/generated/rpc-tx-status-page-model.json";
import rpcEXPERIMENTALValidatorsOrderedPageModel from "../standalone/generated/rpc-EXPERIMENTAL-validators-ordered-page-model.json";
import rpcValidatorsByEpochPageModel from "../standalone/generated/rpc-validators-by-epoch-page-model.json";
import rpcValidatorsCurrentPageModel from "../standalone/generated/rpc-validators-current-page-model.json";
import fastnearSystemHealthPageModel from "../standalone/generated/fastnear-system-health-page-model.json";
import fastnearSystemStatusPageModel from "../standalone/generated/fastnear-system-status-page-model.json";
import fastnearV0AccountStakingPageModel from "../standalone/generated/fastnear-v0-account-staking-page-model.json";
import fastnearV0AccountFtPageModel from "../standalone/generated/fastnear-v0-account-ft-page-model.json";
import fastnearV0AccountNftPageModel from "../standalone/generated/fastnear-v0-account-nft-page-model.json";
import fastnearV0PublicKeyLookupPageModel from "../standalone/generated/fastnear-v0-public-key-lookup-page-model.json";
import fastnearV0PublicKeyLookupAllPageModel from "../standalone/generated/fastnear-v0-public-key-lookup-all-page-model.json";
import fastnearV1AccountStakingPageModel from "../standalone/generated/fastnear-v1-account-staking-page-model.json";
import fastnearV1AccountFtPageModel from "../standalone/generated/fastnear-v1-account-ft-page-model.json";
import fastnearV1AccountNftPageModel from "../standalone/generated/fastnear-v1-account-nft-page-model.json";
import fastnearV1AccountFullPageModel from "../standalone/generated/fastnear-v1-account-full-page-model.json";
import fastnearV1PublicKeyLookupPageModel from "../standalone/generated/fastnear-v1-public-key-lookup-page-model.json";
import fastnearV1FtTopPageModel from "../standalone/generated/fastnear-v1-ft-top-page-model.json";
import fastnearV1PublicKeyLookupAllPageModel from "../standalone/generated/fastnear-v1-public-key-lookup-all-page-model.json";
import kvFastdataV0AllByPredecessorPageModel from "../standalone/generated/kv-fastdata-v0-all-by-predecessor-page-model.json";
import kvFastdataV0HistoryByKeyPageModel from "../standalone/generated/kv-fastdata-v0-history-by-key-page-model.json";
import kvFastdataV0HistoryByAccountPageModel from "../standalone/generated/kv-fastdata-v0-history-by-account-page-model.json";
import kvFastdataV0HistoryByPredecessorPageModel from "../standalone/generated/kv-fastdata-v0-history-by-predecessor-page-model.json";
import kvFastdataV0GetHistoryKeyPageModel from "../standalone/generated/kv-fastdata-v0-get-history-key-page-model.json";
import kvFastdataV0LatestByAccountPageModel from "../standalone/generated/kv-fastdata-v0-latest-by-account-page-model.json";
import kvFastdataV0LatestByPredecessorPageModel from "../standalone/generated/kv-fastdata-v0-latest-by-predecessor-page-model.json";
import kvFastdataV0GetLatestKeyPageModel from "../standalone/generated/kv-fastdata-v0-get-latest-key-page-model.json";
import kvFastdataV0MultiPageModel from "../standalone/generated/kv-fastdata-v0-multi-page-model.json";
import neardataSystemHealthPageModel from "../standalone/generated/neardata-system-health-page-model.json";
import neardataV0FirstBlockPageModel from "../standalone/generated/neardata-v0-first-block-page-model.json";
import neardataV0BlockPageModel from "../standalone/generated/neardata-v0-block-page-model.json";
import neardataV0BlockHeadersPageModel from "../standalone/generated/neardata-v0-block-headers-page-model.json";
import neardataV0BlockChunkPageModel from "../standalone/generated/neardata-v0-block-chunk-page-model.json";
import neardataV0BlockShardPageModel from "../standalone/generated/neardata-v0-block-shard-page-model.json";
import neardataV0BlockOptimisticPageModel from "../standalone/generated/neardata-v0-block-optimistic-page-model.json";
import neardataV0LastBlockFinalPageModel from "../standalone/generated/neardata-v0-last-block-final-page-model.json";
import neardataV0LastBlockOptimisticPageModel from "../standalone/generated/neardata-v0-last-block-optimistic-page-model.json";
import transactionsV0AccountPageModel from "../standalone/generated/transactions-v0-account-page-model.json";
import transactionsV0BlockPageModel from "../standalone/generated/transactions-v0-block-page-model.json";
import transactionsV0BlocksPageModel from "../standalone/generated/transactions-v0-blocks-page-model.json";
import transactionsV0ReceiptPageModel from "../standalone/generated/transactions-v0-receipt-page-model.json";
import transactionsV0TransactionsPageModel from "../standalone/generated/transactions-v0-transactions-page-model.json";
import transfersV0TransfersPageModel from "../standalone/generated/transfers-v0-transfers-page-model.json";

export type GeneratedFastnearPageModel =
  | typeof rpcViewAccessKeyPageModel
  | typeof rpcViewAccessKeyListPageModel
  | typeof rpcViewAccountPageModel
  | typeof rpcBlockByHeightPageModel
  | typeof rpcBlockByIdPageModel
  | typeof rpcBlockEffectsPageModel
  | typeof rpcCallFunctionPageModel
  | typeof rpcViewCodePageModel
  | typeof rpcViewGlobalContractCodePageModel
  | typeof rpcViewGlobalContractCodeByAccountIdPageModel
  | typeof rpcViewStatePageModel
  | typeof rpcEXPERIMENTALCongestionLevelPageModel
  | typeof rpcEXPERIMENTALLightClientBlockProofPageModel
  | typeof rpcEXPERIMENTALLightClientProofPageModel
  | typeof rpcEXPERIMENTALProtocolConfigPageModel
  | typeof rpcEXPERIMENTALSplitStorageInfoPageModel
  | typeof rpcChangesPageModel
  | typeof rpcChunkByBlockShardPageModel
  | typeof rpcChunkByHashPageModel
  | typeof rpcClientConfigPageModel
  | typeof rpcGasPricePageModel
  | typeof rpcGasPriceByBlockPageModel
  | typeof rpcGenesisConfigPageModel
  | typeof rpcHealthPageModel
  | typeof rpcLatestBlockPageModel
  | typeof rpcLightClientProofPageModel
  | typeof rpcMaintenanceWindowsPageModel
  | typeof rpcMetricsPageModel
  | typeof rpcNetworkInfoPageModel
  | typeof rpcNextLightClientBlockPageModel
  | typeof rpcStatusPageModel
  | typeof rpcEXPERIMENTALReceiptPageModel
  | typeof rpcEXPERIMENTALTxStatusPageModel
  | typeof rpcBroadcastTxAsyncPageModel
  | typeof rpcBroadcastTxCommitPageModel
  | typeof rpcSendTxPageModel
  | typeof rpcTxStatusPageModel
  | typeof rpcEXPERIMENTALValidatorsOrderedPageModel
  | typeof rpcValidatorsByEpochPageModel
  | typeof rpcValidatorsCurrentPageModel
  | typeof fastnearSystemHealthPageModel
  | typeof fastnearSystemStatusPageModel
  | typeof fastnearV0AccountStakingPageModel
  | typeof fastnearV0AccountFtPageModel
  | typeof fastnearV0AccountNftPageModel
  | typeof fastnearV0PublicKeyLookupPageModel
  | typeof fastnearV0PublicKeyLookupAllPageModel
  | typeof fastnearV1AccountStakingPageModel
  | typeof fastnearV1AccountFtPageModel
  | typeof fastnearV1AccountNftPageModel
  | typeof fastnearV1AccountFullPageModel
  | typeof fastnearV1PublicKeyLookupPageModel
  | typeof fastnearV1FtTopPageModel
  | typeof fastnearV1PublicKeyLookupAllPageModel
  | typeof kvFastdataV0AllByPredecessorPageModel
  | typeof kvFastdataV0HistoryByKeyPageModel
  | typeof kvFastdataV0HistoryByAccountPageModel
  | typeof kvFastdataV0HistoryByPredecessorPageModel
  | typeof kvFastdataV0GetHistoryKeyPageModel
  | typeof kvFastdataV0LatestByAccountPageModel
  | typeof kvFastdataV0LatestByPredecessorPageModel
  | typeof kvFastdataV0GetLatestKeyPageModel
  | typeof kvFastdataV0MultiPageModel
  | typeof neardataSystemHealthPageModel
  | typeof neardataV0FirstBlockPageModel
  | typeof neardataV0BlockPageModel
  | typeof neardataV0BlockHeadersPageModel
  | typeof neardataV0BlockChunkPageModel
  | typeof neardataV0BlockShardPageModel
  | typeof neardataV0BlockOptimisticPageModel
  | typeof neardataV0LastBlockFinalPageModel
  | typeof neardataV0LastBlockOptimisticPageModel
  | typeof transactionsV0AccountPageModel
  | typeof transactionsV0BlockPageModel
  | typeof transactionsV0BlocksPageModel
  | typeof transactionsV0ReceiptPageModel
  | typeof transactionsV0TransactionsPageModel
  | typeof transfersV0TransfersPageModel
;

export const ALL_PAGE_MODELS: GeneratedFastnearPageModel[] = [
  rpcViewAccessKeyPageModel,
  rpcViewAccessKeyListPageModel,
  rpcViewAccountPageModel,
  rpcBlockByHeightPageModel,
  rpcBlockByIdPageModel,
  rpcBlockEffectsPageModel,
  rpcCallFunctionPageModel,
  rpcViewCodePageModel,
  rpcViewGlobalContractCodePageModel,
  rpcViewGlobalContractCodeByAccountIdPageModel,
  rpcViewStatePageModel,
  rpcEXPERIMENTALCongestionLevelPageModel,
  rpcEXPERIMENTALLightClientBlockProofPageModel,
  rpcEXPERIMENTALLightClientProofPageModel,
  rpcEXPERIMENTALProtocolConfigPageModel,
  rpcEXPERIMENTALSplitStorageInfoPageModel,
  rpcChangesPageModel,
  rpcChunkByBlockShardPageModel,
  rpcChunkByHashPageModel,
  rpcClientConfigPageModel,
  rpcGasPricePageModel,
  rpcGasPriceByBlockPageModel,
  rpcGenesisConfigPageModel,
  rpcHealthPageModel,
  rpcLatestBlockPageModel,
  rpcLightClientProofPageModel,
  rpcMaintenanceWindowsPageModel,
  rpcMetricsPageModel,
  rpcNetworkInfoPageModel,
  rpcNextLightClientBlockPageModel,
  rpcStatusPageModel,
  rpcEXPERIMENTALReceiptPageModel,
  rpcEXPERIMENTALTxStatusPageModel,
  rpcBroadcastTxAsyncPageModel,
  rpcBroadcastTxCommitPageModel,
  rpcSendTxPageModel,
  rpcTxStatusPageModel,
  rpcEXPERIMENTALValidatorsOrderedPageModel,
  rpcValidatorsByEpochPageModel,
  rpcValidatorsCurrentPageModel,
  fastnearSystemHealthPageModel,
  fastnearSystemStatusPageModel,
  fastnearV0AccountStakingPageModel,
  fastnearV0AccountFtPageModel,
  fastnearV0AccountNftPageModel,
  fastnearV0PublicKeyLookupPageModel,
  fastnearV0PublicKeyLookupAllPageModel,
  fastnearV1AccountStakingPageModel,
  fastnearV1AccountFtPageModel,
  fastnearV1AccountNftPageModel,
  fastnearV1AccountFullPageModel,
  fastnearV1PublicKeyLookupPageModel,
  fastnearV1FtTopPageModel,
  fastnearV1PublicKeyLookupAllPageModel,
  kvFastdataV0AllByPredecessorPageModel,
  kvFastdataV0HistoryByKeyPageModel,
  kvFastdataV0HistoryByAccountPageModel,
  kvFastdataV0HistoryByPredecessorPageModel,
  kvFastdataV0GetHistoryKeyPageModel,
  kvFastdataV0LatestByAccountPageModel,
  kvFastdataV0LatestByPredecessorPageModel,
  kvFastdataV0GetLatestKeyPageModel,
  kvFastdataV0MultiPageModel,
  neardataSystemHealthPageModel,
  neardataV0FirstBlockPageModel,
  neardataV0BlockPageModel,
  neardataV0BlockHeadersPageModel,
  neardataV0BlockChunkPageModel,
  neardataV0BlockShardPageModel,
  neardataV0BlockOptimisticPageModel,
  neardataV0LastBlockFinalPageModel,
  neardataV0LastBlockOptimisticPageModel,
  transactionsV0AccountPageModel,
  transactionsV0BlockPageModel,
  transactionsV0BlocksPageModel,
  transactionsV0ReceiptPageModel,
  transactionsV0TransactionsPageModel,
  transfersV0TransfersPageModel,
];

export {
  rpcViewAccessKeyPageModel,
  rpcViewAccessKeyListPageModel,
  rpcViewAccountPageModel,
  rpcBlockByHeightPageModel,
  rpcBlockByIdPageModel,
  rpcBlockEffectsPageModel,
  rpcCallFunctionPageModel,
  rpcViewCodePageModel,
  rpcViewGlobalContractCodePageModel,
  rpcViewGlobalContractCodeByAccountIdPageModel,
  rpcViewStatePageModel,
  rpcEXPERIMENTALCongestionLevelPageModel,
  rpcEXPERIMENTALLightClientBlockProofPageModel,
  rpcEXPERIMENTALLightClientProofPageModel,
  rpcEXPERIMENTALProtocolConfigPageModel,
  rpcEXPERIMENTALSplitStorageInfoPageModel,
  rpcChangesPageModel,
  rpcChunkByBlockShardPageModel,
  rpcChunkByHashPageModel,
  rpcClientConfigPageModel,
  rpcGasPricePageModel,
  rpcGasPriceByBlockPageModel,
  rpcGenesisConfigPageModel,
  rpcHealthPageModel,
  rpcLatestBlockPageModel,
  rpcLightClientProofPageModel,
  rpcMaintenanceWindowsPageModel,
  rpcMetricsPageModel,
  rpcNetworkInfoPageModel,
  rpcNextLightClientBlockPageModel,
  rpcStatusPageModel,
  rpcEXPERIMENTALReceiptPageModel,
  rpcEXPERIMENTALTxStatusPageModel,
  rpcBroadcastTxAsyncPageModel,
  rpcBroadcastTxCommitPageModel,
  rpcSendTxPageModel,
  rpcTxStatusPageModel,
  rpcEXPERIMENTALValidatorsOrderedPageModel,
  rpcValidatorsByEpochPageModel,
  rpcValidatorsCurrentPageModel,
  fastnearSystemHealthPageModel,
  fastnearSystemStatusPageModel,
  fastnearV0AccountStakingPageModel,
  fastnearV0AccountFtPageModel,
  fastnearV0AccountNftPageModel,
  fastnearV0PublicKeyLookupPageModel,
  fastnearV0PublicKeyLookupAllPageModel,
  fastnearV1AccountStakingPageModel,
  fastnearV1AccountFtPageModel,
  fastnearV1AccountNftPageModel,
  fastnearV1AccountFullPageModel,
  fastnearV1PublicKeyLookupPageModel,
  fastnearV1FtTopPageModel,
  fastnearV1PublicKeyLookupAllPageModel,
  kvFastdataV0AllByPredecessorPageModel,
  kvFastdataV0HistoryByKeyPageModel,
  kvFastdataV0HistoryByAccountPageModel,
  kvFastdataV0HistoryByPredecessorPageModel,
  kvFastdataV0GetHistoryKeyPageModel,
  kvFastdataV0LatestByAccountPageModel,
  kvFastdataV0LatestByPredecessorPageModel,
  kvFastdataV0GetLatestKeyPageModel,
  kvFastdataV0MultiPageModel,
  neardataSystemHealthPageModel,
  neardataV0FirstBlockPageModel,
  neardataV0BlockPageModel,
  neardataV0BlockHeadersPageModel,
  neardataV0BlockChunkPageModel,
  neardataV0BlockShardPageModel,
  neardataV0BlockOptimisticPageModel,
  neardataV0LastBlockFinalPageModel,
  neardataV0LastBlockOptimisticPageModel,
  transactionsV0AccountPageModel,
  transactionsV0BlockPageModel,
  transactionsV0BlocksPageModel,
  transactionsV0ReceiptPageModel,
  transactionsV0TransactionsPageModel,
  transfersV0TransfersPageModel,
};
